apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dbconnections.my.crds
spec:
  group: my.crds
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dbType:
                  type: string
                defaultSchema:
                  type: string
                capacityGb:
                  type: integer
                configMapRef:
                  type: string
                rootUser:
                  type: string
                rootPassword:
                  type: string
  scope: Namespaced
  names:
    plural: dbconnections
    singular: dbconnection
    kind: DbConnection
    shortNames:
    - dbconn
