apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
  labels:
    app: nginx
    env: test
spec:
  containers:
  - name: app-busybox
    image: 'radial/busyboxplus:curl'
    command: [ 'sh', '-c', 'while true; do sleep 3600; done']
