apiVersion: v1
kind: Pod
metadata: 
  name: init-pod
spec:
  initContainers:
  - name: delay
    image: busybox
    command: ['sleep', '30']
  - name: delay2
    image: busybox
    command: ['sleep', '5']
  containers:
  - name: nginx
    image: nginx:1.19.1
