apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: user-request-devops
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0daR1YyYjNCek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXNxaDhpaUdPOVJyS3J3VW8zUE12WGg2S2NFdGNmSzc5STZhRVVidnpnN2tsClFEN0o2WnRQVmJXaFg2MTVmRVV1ampxYWtxQjdRb3NOcEJDYmdOQkYyN1dxWUNxSWdRZ25LTlhHbHFXTTVjNFgKWlo5a2N1ZWtTZGoydzJUMU43L1Z0d1BCYUIzU0tFcGFJakZzQldsWWdjZWJmQ0ZRd0pKT0orRjJDNVNYZ1lvTwo3SE9qRWFPYjJQUjFOdi8zYzkza3NOY3JvTndSRFp6QnNLMk9zNE14OCt6UmlyK2ZaUlQvQTF1cXlNbnRreTV0ClNPSzlTWVMzQm1Na0xNRXFmS2IwZUsyczZ5eHFGTXVMRWhUTG1xUXIvTlVnbDZXYTZHRVc5cndXVVg5Z0ZoblUKQnVUT0U5ME1kMUFybnBFY1poZ2E3Y1hpTjV2SEp5QktqRGtFa29vWVd3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQlNYajJIUFJ2ajZXcnFldllDL0Q2OGJwQlpxYWtXZjFuZkoxRHBTU1duTU1wU0FtTUhmClBhc1pOK2xBSCtFa1drTWxHM0pnWVVQZTZKQi9GOTFQL2pJeWViSE9TZUg4cXB4REJzZE42SU5lNXFLTTd4UjUKejFFb2lld0xNbGJrOEFsZE5hUHg4VVZGK05WSTJvVHpzcFlVY01PK2R0RjVJNTRXZXUzeVNrSHpTZ0tucVJkRQpnWFk2Rndhc25JRmZuL29hV0pjNjZvSE5KZlZGSHI4WkkxUEJrMU5qamtpczNZQzRORlA5NXpVcExGTlNHL0ZjCnB4cGNTc1llTUxzRnZlZ2xycnExK29LRG5hNjQ5RmNVTzhvRFAwdUZkL1hqYjBpOGVVNWdvS0txWGRveVJYKzAKRi9ISWFnT3c2Sk0xRkZHWGJMTG1HcGt3anVqTWdMZkhmc0E9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 315569260
  usages:
  - digital signature
  - key encipherment
  - client auth
