apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: loadbalancer-web-svc
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.190.40
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
