apiVersion: apps/v1 
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: nginx-pod
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
