apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
  labels:
    app: logging
spec:
  selector:
    matchLabels:
      app: logging 
  template:
    metadata:
      labels:
        app: logging
    spec:
      containers:
        - name: nginx
          image: nginx
